### PR TITLE
Fix cross compilation on android armv7 and x86

### LINKED ISSUE #175: Android: Unknown processor CMAKE_SYSTEM_PROCESSOR=arm
When this happens，CMAKE_SYSTEM_PROCESSOR should be armv7-a，not arm

### PR DESCRIPTION
**Pull request by fredszaq**
This fixes the following cmake errors

```
Android: Unknown processor CMAKE_SYSTEM_PROCESSOR='x86'.
```
and

```
Android: Unknown processor CMAKE_SYSTEM_PROCESSOR='arm'.
```

when crosscompiling for `i686-linux-android` and `armv7-linux-androideabi` android targets

fixes #175

### CODE REVIEW

**Comment by ThibautLorrainSonos** [comment]
the ci fails on  mips crosscompile test as rustup can't download those targets that were retrogaded to tier 3 https://github.com/rust-lang/compiler-team/issues/648

**Comment by fredszaq** [comment]
the ci fails on mips crosscompile test as rustup can't download those targets that were retrogaded to tier 3 https://github.com/rust-lang/compiler-team/issues/648

**Comment by FlorianDenis** [comment]
I confirm this solves issues cross-compiling for Android, would love to see this merged

**Comment by MihirLuthra** [comment]
Yes, this solves the issue.
@thomcc, pinging you since you seem to be an active reviewer of `cmake-rs` 🙂. Please ignore if this PR falls out of your scope.

**Pull request merged**
